# Generated by @olympio/quality-config
# Do NOT hardcode tokens here. Use SONAR_TOKEN env var.

sonar.projectKey={{PROJECT_KEY}}
sonar.projectName={{PROJECT_NAME}}
sonar.projectVersion=1.0

# Sources
sonar.sources={{SOURCES}}
sonar.tests={{TESTS}}
sonar.test.inclusions={{TEST_INCLUSIONS}}

# Exclusions
sonar.exclusions={{EXCLUSIONS}}

# Encoding
sonar.sourceEncoding={{SOURCE_ENCODING}}

# Duplicated code
sonar.cpd.minimumTokens=50
sonar.cpd.minimumLines=10

# Secrets detection
sonar.text.secrets.enabled=true
sonar.text.inclusions=**/*.ts,**/*.tsx,**/*.js,**/*.jsx,**/*.py,**/*.json,**/*.env*,**/*.yml,**/*.yaml

# Security hotspots
sonar.security.hotspots.enabled=true

# SCM
sonar.scm.provider=git

{{EXTRA_PROPERTIES}}
