#!/bin/bash

# =====================================================
# LGPD Compliance Report Generator
# @olympio/quality-config
# =====================================================

echo "Generating LGPD Compliance Report..."
echo "=============================================="
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

REPORT_DATE=$(date +"%Y-%m-%d_%H-%M-%S")
REPORT_DIR="./reports/lgpd"
REPORT_FILE="$REPORT_DIR/compliance_report_$REPORT_DATE.md"

mkdir -p "$REPORT_DIR"

PROJECT_NAME=$(basename "$(pwd)")

cat > "$REPORT_FILE" << EOF
# LGPD Compliance Report
**Date**: $(date +"%d/%m/%Y %H:%M:%S")
**Project**: $PROJECT_NAME

---

## 1. Executive Summary

This report provides an overview of LGPD compliance status for the project.

EOF

echo -e "${GREEN}[ok]${NC} Section: Executive Summary"

cat >> "$REPORT_FILE" << 'EOF'

## 2. Compliance Checklist

### Legal Basis (Art. 7 LGPD)
- [ ] Documented consent
- [ ] Specific purpose defined
- [ ] Justified necessity
- [ ] Transparency implemented

### Security (Art. 46 LGPD)
- [ ] Encryption in transit (HTTPS)
- [ ] Encryption at rest
- [ ] Access control (RLS/RBAC)
- [ ] Audit logging
- [ ] Regular backups

### Data Subject Rights (Art. 18 LGPD)
- [ ] Data access implemented
- [ ] Data correction implemented
- [ ] Data deletion implemented
- [ ] Data portability implemented
- [ ] Consent revocation implemented

### Governance
- [ ] DPO designated
- [ ] Data inventory maintained
- [ ] Privacy policy updated
- [ ] Retention policies defined
- [ ] Incident response plan

## 3. Code Analysis

Run SonarQube with LGPD rules:
```bash
# Local
docker compose -f docker-compose.sonar.yml up -d
npx sonarqube-scanner

# Or via CI (GitHub Actions)
# Triggered automatically on push/PR
```

## 4. Recommendations

### Immediate Actions
1. Review pending deletion requests
2. Verify consent status
3. Audit sensitive data access

### Medium-term Actions
1. Implement retention policy automation
2. Create compliance dashboard
3. Train team on LGPD

### Long-term Actions
1. ISO 27001 certification
2. External audit
3. Implement Privacy by Design

## 5. Metrics

- **Consent Rate**: Calculate
- **Average Response Time**: Calculate
- **Security Incidents**: 0 (last month)
- **Requests Fulfilled**: Calculate

## 6. Next Review

**Date**: TBD

---

**Generated by**: @olympio/quality-config
EOF

echo -e "${GREEN}[ok]${NC} Section: Compliance Checklist"
echo -e "${GREEN}[ok]${NC} Section: Recommendations"
echo ""
echo -e "${GREEN}Report generated successfully!${NC}"
echo -e "File: ${YELLOW}$REPORT_FILE${NC}"
echo ""

if command -v pandoc &> /dev/null; then
    HTML_FILE="${REPORT_FILE%.md}.html"
    pandoc "$REPORT_FILE" -o "$HTML_FILE" --standalone 2>/dev/null
    if [ $? -eq 0 ]; then
        echo -e "${GREEN}[ok]${NC} HTML version generated: $HTML_FILE"
    fi
fi

echo "=============================================="
echo "LGPD Compliance Report Complete"
